Add documentation
engsoft-2023/new-frontend pull request #16
Opened 2023-12-09 07:33 UTC by erickrodrigs

2023-12-09 19:59 UTC, LeiteJu requested changes

2023-12-09 19:59 UTC, LeiteJu commented on README.md
> +A visualização conta ainda com uma lista de métricas daquele sistema. As métricas são divididas em globas (aquelas referentes ao sistema como um todo) e específicas (para um único serviço). As métric
Acredito que aqui deveria ser "... As métricas são divididas em gabais ..." ao invés de "globas"

2023-12-09 19:59 UTC, LeiteJu commented on README.md
> +No passo (2), a plataforma trás todos os serviços identificados no passo anterior e pede ao usuário que informe os arquivos open-api que descreve a API de cada serviço. O usuário pode informar o cami
Aqui deveria ser "... a plataforma traz..." do verbo "trazer"

2023-12-12 00:01 UTC, DerickWMFrias approved these changes

2023-12-12 00:05 UTC, DerickWMFrias approved these changes

2023-12-12 00:14 UTC, gabrielhpr approved these changes

2023-12-12 00:19 UTC, merged